apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umbrella-dtr-patch
  annotations:
    {{- with .Values.dtr.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{/*    nginx.ingress.kubernetes.io/rewrite-target: /*/}}
spec:
  rules:
    {{- range .Values.dtr.hosts}}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ $.Values.dtr.service.port }}
    {{- end}}